FROM node:latest

WORKDIR /app

RUN npm i -g pnpm@latest
RUN npm i -g prisma@latest

COPY package*.json ./

RUN pnpm i

COPY . .

RUN prisma generate

COPY --chown=node:node . .

EXPOSE 3001

CMD [ "pnpm", "run", "dev" ]